---
- name: Complete Maven-Docker Deployment Pipeline
  hosts: env_dev
  become: yes
  gather_facts: yes
  
  vars_files:
    - group_vars/all.yaml
    - vault.yaml
  
  pre_tasks:
    - name: Wait for system to be ready
      wait_for_connection:
        timeout: 300
      
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false
  
  roles:
    - deploy_app
  
  post_tasks:
    - name: Display deployment summary
      debug:
        msg:
          - "Deployment completed successfully!"
          - "Docker image: {{ docker_image_name }}:{{ docker_tag }}"
          - "Repository: {{ git_repo_url }}"
          
  handlers:
    - name: restart docker
      service:
        name: docker
        state: restarted
