---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1

filters:
  tag:Environment: dev
  tag:Role: web
  instance-state-name: running

# Use public IP for connection
compose:
  ansible_host: public_ip_address

# Group instances by tags
keyed_groups:
  - key: tags.Name
    prefix: name
    separator: "_"
  - key: tags.Environment
    prefix: env
  - key: tags.Role
    prefix: role

# Set hostnames to instance name tags
hostnames:
  - tag:Name

# Cache settings for better performance
cache: true
cache_plugin: jsonfile
cache_timeout: 300
cache_connection: /tmp/aws_ec2_inventory_cache
cache_prefix: aws_ec2
